name: Demanda diaria (alt)

on:
  workflow_dispatch: 
  schedule:
    - cron: '20 18 * * *'  # Runs daily at midnight
  
jobs:
  run-r-script:
    outputs:
      datetime: ${{ env.datetime }}
      artifact-url: ${{ steps.upload-plot-artifact.outputs.artifact-url }} 
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      # baja script, demanda_diaria*.txt y renv.lock
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: echo "datetime=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV      
    - run: sudo apt-get update && sudo apt-get install -qq r-base
    - uses: r-lib/actions/setup-r@v2
      with:                 # esto debería ser más rápido además la imagen de ubuntu
        install-r: false    # usa el repo de https://cloud.r-project.org/bin/linux/ubuntu/
    - uses: r-lib/actions/setup-renv@v2
    - id: cortes_ENRE            # actualiza cortes_ENRE para incluir en el gráfico.
      continue-on-error: true  
      run: Rscript cortes_ENRE.R
    - run: git restore cortes.csv                         # en teoría esto no sería
      if: ${{ steps.cortes_ENRE.outcome != "success" }}   # tan necesario (el csv no se pisa)  
    - id: generar_grafico
      run: Rscript demanda_diaria_API_MEM.R               # generar gráfico
    - run: mv demanda_diaria.png demanda_diaria_${{ env.datetime }}.png
    - id: upload_plot_artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}_demanda_diaria_${{ env.datetime }}
        path: demanda_diaria_${{ env.datetime }}.png
    - run: git add demanda_diaria_Edesur.txt demanda_diaria_GBA.txt cortes_ENRE.csv
    #    if ! git diff-index --quiet HEAD ; then echo "must_commit=yes" >> $GITHUB_ENV ; fi
    # ^ https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
    - id: git_push
    - run: |
        git commit -m "Actions run_id=${{ github.run_id }}, dt=${{ env.datetime }}"
        git push
    - continue-on-error: true
    - run: echo "::warning ::El repositorio no se actualizó"
    - if: ${{ steps.git_push.outcome != "success" }}
  send-email:
    runs-on: ubuntu-latest
    needs: run-r-script
    env:
      datetime: ${{ needs.run-r-script.outputs.datetime }}
      artifact-url: ${{ needs.run-r-script.outputs.artifact-url }}      
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}_demanda_diaria_${{ env.datetime }}
     # - name: Convert image to base64
     #   id: base64_image
     #   run: |
     #     BASE64_IMAGE=$(base64 -w 0 demanda_diaria_${{ env.datetime }}.png)
     #     # Store in step outputs, escaping the content
     #     echo "base64_content=$BASE64_IMAGE" >> $GITHUB_OUTPUT
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Notification
          html_body: | 
            <h3 id="informe-de-demanda-diaria">Informe de demanda diaria</h3>
            <p>Fecha de ejecución: ${{ env.datetime }}</p>
            <p><img src="cid:demanda_diaria_${{ env.datetime }}.png" alt="Chart" /></p>
            <hr />
            <p>Email generado en forma automática</p>
          # Dirección obtenida para grupo de teams
          attachments: demanda_diaria_${{ env.datetime }}.png
          to: 7fd2381b.enelcom.onmicrosoft.com@emea.teams.ms
          from: Ricardo via GitHub Actions <noreply@github.com>

