name: download data cache

on:
  workflow_dispatch:
  
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Cache data files
      uses: actions/cache@v4
      with:
        path: |
          demanda_diaria_Edesur.txt
          demanda_diaria_GBA.txt
        key: ${{ runner.os }}-data

    - name: Upload data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: demanda_diaria_data
        path: |
          demanda_diaria_Edesur.txt
          demanda_diaria_GBA.txt
